version: '3'
services:
 postgres:
  build: ./banco
  image: s2/banco
  ports: 
    - "5433:5432"
 web:
  build: .
  image: dac/app
  ports: 
    - "8082:8080" 
  links: 
    - "postgres:host-banco"   